### ISSUE TITLE
`0.11.28` break API docs after upgrading from `v0.11.27`

### ISSUE THREAD

**Issue by MarJose123** [dedoc/scramble#642]
After upgrading to `0.11.28` the `/docs/api/` returns an error 

```txt
 local.ERROR: Dedoc\Scramble\Support\Generator\TypeTransformer::transform(): Argument #1 ($type) must be of type Dedoc\Scramble\Support\Type\Type, null given, 
```

the `/docs/api/` is properly working on  `v0.11.27`

**Comment by MarJose123** [comment]
here is the entire stack trace.

```txt
[2024-11-28 00:14:54] local.ERROR: Dedoc\Scramble\Support\Generator\TypeTransformer::transform(): Argument #1 ($type) must be of type Dedoc\Scramble\Support\Type\Type, null given, called in C:\Users\Admin\Documents\Self-Project\ninshiki-backend\vendor\dedoc\scramble\src\Support\TypeToSchemaExtensions\ModelToSchema.php on line 31 {"exception":"[object] (TypeError(code: 0): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer::transform(): Argument #1 ($type) must be of type Dedoc\\Scramble\\Support\\Type\\Type, null given, called in C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\TypeToSchemaExtensions\\ModelToSchema.php on line 31 at C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php:60)
[stacktrace]
#0 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\TypeToSchemaExtensions\\ModelToSchema.php(31): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->transform(NULL)
#1 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(248): Dedoc\\Scramble\\Support\\TypeToSchemaExtensions\\ModelToSchema->toSchema(Object(Dedoc\\Scramble\\Support\\Type\\ObjectType), NULL)
#2 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php(818): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->Dedoc\\Scramble\\Support\\Generator\\{closure}(NULL, Object(Dedoc\\Scramble\\Support\\TypeToSchemaExtensions\\ModelToSchema), 0)
#3 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(247): Illuminate\\Support\\Collection->reduce(Object(Closure))
#4 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(204): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->handleUsingExtensions(Object(Dedoc\\Scramble\\Support\\Type\\ObjectType))
#5 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\TypeToSchemaExtensions\\LengthAwarePaginatorTypeToSchema.php(41): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->transform(Object(Dedoc\\Scramble\\Support\\Type\\ObjectType))
#6 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(248): Dedoc\\Scramble\\Support\\TypeToSchemaExtensions\\LengthAwarePaginatorTypeToSchema->toSchema(Object(Dedoc\\Scramble\\Support\\Type\\Generic), NULL)
#7 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Traits\\EnumeratesValues.php(818): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->Dedoc\\Scramble\\Support\\Generator\\{closure}(NULL, Object(Dedoc\\Scramble\\Support\\TypeToSchemaExtensions\\LengthAwarePaginatorTypeToSchema), 0)
#8 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(247): Illuminate\\Support\\Collection->reduce(Object(Closure))
#9 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(204): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->handleUsingExtensions(Object(Dedoc\\Scramble\\Support\\Type\\Generic))
#10 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\TypeToSchemaExtensions\\LengthAwarePaginatorTypeToSchema.php(81): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->transform(Object(Dedoc\\Scramble\\Support\\Type\\Generic))
#11 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(321): Dedoc\\Scramble\\Support\\TypeToSchemaExtensions\\LengthAwarePaginatorTypeToSchema->toResponse(Object(Dedoc\\Scramble\\Support\\Type\\Generic), NULL)
#12 [internal function]: Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->Dedoc\\Scramble\\Support\\Generator\\{closure}(NULL, 'Dedoc\\\\Scramble\\\\...')
#13 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(312): array_reduce(Array, Object(Closure))
#14 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\Generator\\TypeTransformer.php(274): Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->handleResponseUsingExtensions(Object(Dedoc\\Scramble\\Support\\Type\\Generic))
#15 [internal function]: Dedoc\\Scramble\\Support\\Generator\\TypeTransformer->toResponse(Object(Dedoc\\Scramble\\Support\\Type\\Generic), 0)
#16 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php(609): array_map(Object(Closure), Array, Array)
#17 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(795): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#18 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\OperationExtensions\\ResponseExtension.php(32): Illuminate\\Support\\Collection->map(Object(Closure))
#19 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Support\\OperationBuilder.php(30): Dedoc\\Scramble\\Support\\OperationExtensions\\ResponseExtension->handle(Object(Dedoc\\Scramble\\Support\\Generator\\Operation), Object(Dedoc\\Scramble\\Support\\RouteInfo))
#20 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Generator.php(187): Dedoc\\Scramble\\Support\\OperationBuilder->build(Object(Dedoc\\Scramble\\Support\\RouteInfo), Object(Dedoc\\Scramble\\Support\\Generator\\OpenApi), Object(Dedoc\\Scramble\\GeneratorConfig))
#21 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Generator.php(59): Dedoc\\Scramble\\Generator->routeToOperation(Object(Dedoc\\Scramble\\Support\\Generator\\OpenApi), Object(Illuminate\\Routing\\Route), Object(Dedoc\\Scramble\\GeneratorConfig))
#22 [internal function]: Dedoc\\Scramble\\Generator->Dedoc\\Scramble\\{closure}(Object(Illuminate\\Routing\\Route), 13)
#23 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Arr.php(609): array_map(Object(Closure), Array, Array)
#24 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Collections\\Collection.php(795): Illuminate\\Support\\Arr::map(Array, Object(Closure))
#25 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Generator.php(57): Illuminate\\Support\\Collection->map(Object(Closure))
#26 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Scramble.php(161): Dedoc\\Scramble\\Generator->__invoke(Object(Dedoc\\Scramble\\GeneratorConfig))
#27 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\CallableDispatcher.php(40): Dedoc\\Scramble\\Scramble::Dedoc\\Scramble\\{closure}(Object(Dedoc\\Scramble\\Generator))
#28 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(243): Illuminate\\Routing\\CallableDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Closure))
#29 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(214): Illuminate\\Routing\\Route->runCallable()
#30 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(808): Illuminate\\Routing\\Route->run()
#31 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\dedoc\\scramble\\src\\Http\\Middleware\\RestrictedDocsAccess.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Dedoc\\Scramble\\Http\\Middleware\\RestrictedDocsAccess->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(51): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(88): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#42 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(75): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(807): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#49 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(786): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#50 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(750): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#51 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(739): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#52 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(201): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#53 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#54 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\livewire\\livewire\\src\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\InvokeDeferredCallbacks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#72 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(145): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#73 C:\\Users\\Admin\\Documents\\MyProject\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(1190): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#74 C:\\Users\\Admin\\Documents\\MyProject\\public\\index.php(17): Illuminate\\Foundation\\Application->handleRequest(Object(Illuminate\\Http\\Request))
#75 C:\\Program Files\\Herd\\resources\\app.asar.unpacked\\resources\\valet\\server.php(139): require('C:\\\\Users\\\\Admin\\\\...')
#76 {main}
"} 
```

**Comment by BlackLanzer** [comment]
I have same problem and same stacktrace

**Comment by MarJose123** [comment]
> @BlackLanzer @MarJose123
> 
> Any chance you're using some 3-rd party package from which you extend your models?

I'm using Spatie [Roles-permission](https://spatie.be/docs/laravel-permission/v6/introduction) which I extend in my models.

**Comment by BlackLanzer** [comment]
> @BlackLanzer @MarJose123
> 
> Any chance you're using some 3-rd party package from which you extend your models?

I'm using https://github.com/kirkbushell/eloquence.

Unfortunately I can't show the full source code of the route. I'll try to replicate the problem
